### ISSUE TITLE
Name and value quoting in package.manifest

### ISSUE THREAD

**Issue by lcichanowicz** [Dexmoor/BusinessHours#1]
Hi.  Thanks for a nice Umbraco package.

I was following this article:
https://www.aptitude.co.uk/blog/umbraco-packagemanifest-colour-coding-intellisense-in-visual-studio/

And your package.manifest then gets lots of warnings in VS, because the names and values are not wrapped in double-quotes.  Should they be?

**Comment by jchurchley** [comment]
Hi, thanks for the feedback. I've updated the package.manifest so it's true JSON

#44136ca
