### ISSUE TITLE
Is it possible to set 24 hours format?

### ISSUE THREAD

**Issue by villian** [Dexmoor/BusinessHours#7]

**Comment by jchurchley** [comment]
Hi Oleksandr, 

Not at present but it's a great idea. I'll do a pull request this evening allowing for this.

Cheers

**Comment by villian** [comment]
It would be awesome.

**Comment by jchurchley** [comment]
Hi, started working on an update however ran out of time this evening. The update will require an Umbraco installation greater than 7.12.3 to allow to easily set prevalues in data type prevalues. I'll give it another go tomorrow evening.

**Comment by jchurchley** [comment]
See version 1.2

**Comment by SkrypnikO** [comment]
awesome, thank you so much
